import React, { useEffect, useState } from "react";
import { Button, DatePicker, Input, InputNumber, Select, Tag, message } from "antd";
import dayjs from "dayjs";
import { Flame, Plus, Pause, Play, Trash2 } from "lucide-react";
import Layout from "../components/layout/Layout";
import api from "../api/config";

const initial = { title: "", subtitle: "Limited time offer", badgeText: "FLASH DEAL", discountRate: 10, targetMode: "restaurants", fundingMode: "restaurant", platformSharePercent: 0, restaurantIds: [], menuIds: [], startAt: null, endAt: null, usageLimit: null, perUserLimit: null };

export default function FlashDeals() {
  const [offers, setOffers] = useState([]); const [restaurants, setRestaurants] = useState([]); const [menus, setMenus] = useState([]); const [form, setForm] = useState(initial); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(false);
  const load = async () => { const [o, r] = await Promise.all([api.get("/zone/flash-offers"), api.post("/zone/restaurant-list", { page: 1, limit: 100 })]); setOffers(o.data?.result || []); setRestaurants(r.data?.result || []); };
  useEffect(() => { load().catch(() => message.error("Could not load flash deals")); }, []);
  useEffect(() => { Promise.all(form.restaurantIds.map((id) => api.get(`/zone/restaurant/menu-list/${id}`))).then((rows) => setMenus(rows.flatMap((r) => r.data?.result || []))).catch(() => setMenus([])); }, [form.restaurantIds]);
  const save = async () => { if (!form.title || !form.startAt || !form.endAt || (!form.restaurantIds.length && !form.menuIds.length)) return message.error("Title, dates and a target are required"); setLoading(true); try { const payload = { ...form, startAt: form.startAt.toISOString(), endAt: form.endAt.toISOString() }; if (editing) await api.put(`/zone/flash-offers/${editing}`, payload); else await api.post("/zone/flash-offers", payload); message.success(editing ? "Flash deal updated" : "Flash deal created"); setForm(initial); setEditing(null); load(); } catch (e) { message.error(e.response?.data?.message || "Save failed"); } finally { setLoading(false); } };
  const patchStatus = async (id, status) => { try { await api.patch(`/zone/flash-offers/${id}/status`, { status }); load(); } catch (e) { message.error(e.response?.data?.message || "Status update failed"); } };
  return <Layout><div className="mx-auto max-w-7xl space-y-6 p-4 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.25em] text-blue-600">Campaign management</p><h1 className="text-3xl font-black">Flash Deals</h1></div><Button type="primary" icon={<Plus size={16}/>} onClick={() => { setForm(initial); setEditing(null); }}>New deal</Button></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{offers.map((o) => <div key={o._id} className="rounded-2xl bg-white p-5 shadow-sm border border-slate-200"><div className="flex items-start justify-between gap-3"><div><Tag color="purple">{o.status}</Tag><h3 className="mt-2 text-lg font-bold">{o.title} · {o.discountRate}%</h3><p className="text-slate-500">{o.subtitle}</p><p className="mt-2 text-xs text-slate-500">{new Date(o.startAt).toLocaleString()} → {new Date(o.endAt).toLocaleString()} · Used {o.usedCount || 0}{o.usageLimit ? `/${o.usageLimit}` : ""}</p></div><Flame className="text-pink-600"/></div><div className="mt-4 flex flex-wrap gap-2"><Button size="small" onClick={() => { setEditing(o._id); setForm({ ...o, startAt: dayjs(o.startAt), endAt: dayjs(o.endAt) }); }}>Edit</Button>{o.status === "active" ? <Button size="small" icon={<Pause size={14}/>} onClick={() => patchStatus(o._id, "paused")}>Pause</Button> : <Button size="small" icon={<Play size={14}/>} onClick={() => patchStatus(o._id, "active")}>Activate</Button>}<Button danger size="small" icon={<Trash2 size={14}/>} onClick={() => api.delete(`/zone/flash-offers/${o._id}`).then(load).catch(e => message.error(e.response?.data?.message || "Cannot delete"))}>Delete</Button></div></div>)}{!offers.length && <div className="rounded-2xl bg-white p-10 text-center text-slate-500">No flash deals yet.</div>}</div>
    <div className="rounded-2xl bg-white p-5 shadow-sm border border-slate-200"><h2 className="mb-4 text-xl font-bold">{editing ? "Edit deal" : "Create deal"}</h2><div className="space-y-3"><Input placeholder="Title" value={form.title} onChange={e => setForm({...form,title:e.target.value})}/><Input placeholder="Subtitle" value={form.subtitle} onChange={e => setForm({...form,subtitle:e.target.value})}/><div className="flex gap-2"><Button type={form.discountRate===10?"primary":"default"} onClick={()=>setForm({...form,discountRate:10})}>10%</Button><Button type={form.discountRate===15?"primary":"default"} onClick={()=>setForm({...form,discountRate:15})}>15%</Button><Button type={form.discountRate===20?"primary":"default"} onClick={()=>setForm({...form,discountRate:20})}>20%</Button><InputNumber min={1} max={100} value={form.discountRate} onChange={v=>setForm({...form,discountRate:v})}/></div><Select className="w-full" placeholder="Restaurants" mode="multiple" value={form.restaurantIds} options={restaurants.map(r=>({value:r._id,label:r.name}))} onChange={v=>setForm({...form,restaurantIds:v,targetMode:v.length?"restaurants":form.targetMode})}/><Select className="w-full" placeholder="Optional items" mode="multiple" value={form.menuIds} options={menus.map(m=>({value:m._id,label:m.name}))} onChange={v=>setForm({...form,menuIds:v,targetMode:v.length && form.restaurantIds.length?"restaurant_items":v.length?"items":"restaurants"})}/><Select className="w-full" value={form.fundingMode} options={[{value:"restaurant",label:"Restaurant funded"},{value:"platform",label:"Platform funded"},{value:"split",label:"Split funded"}]} onChange={v=>setForm({...form,fundingMode:v})}/>{form.fundingMode==="split"&&<InputNumber className="w-full" min={0} max={100} addonBefore="Platform share %" value={form.platformSharePercent} onChange={v=>setForm({...form,platformSharePercent:v})}/>}<div className="grid grid-cols-2 gap-2"><DatePicker showTime className="w-full" value={form.startAt} onChange={v=>setForm({...form,startAt:v})}/><DatePicker showTime className="w-full" value={form.endAt} onChange={v=>setForm({...form,endAt:v})}/></div><div className="grid grid-cols-2 gap-2"><InputNumber className="w-full" placeholder="Total limit" value={form.usageLimit} onChange={v=>setForm({...form,usageLimit:v})}/><InputNumber className="w-full" placeholder="Per-user limit" value={form.perUserLimit} onChange={v=>setForm({...form,perUserLimit:v})}/></div><Button block type="primary" loading={loading} onClick={save}>{editing?"Update":"Create"} flash deal</Button></div></div></div></div></Layout>;
}
